version: '3'
services:
    app:
      build:
        context: ./
        dockerfile: Dockerfile
      command: python -m ForwardBot
      volumes:
        - .:/app
      depends_on:
       - db
      links:
       - db
    db:
      container_name: "mongodb_sw_pyro"
      image: mongo:latest
      hostname: mongodb_sw_py
      command: mongod --port 27017
      environment:
        - MONGO_INITDB_DATABASE=mongodb_pyrogram
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass
      ports:
        - '27018:270178'
